version: '3.8'

services:
  web:
    build: .
    container_name: shopping_list
    env_file:
      - .env
    ports:
      - "${APP_PORT:-5000}:5000"
    volumes:
      - .:/app
      - ./database:/app/database
      - ./app/static:/app/static
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    command: >
      gunicorn --bind 0.0.0.0:5000
      --workers 2
      --timeout 120
      --worker-class gthread
      run:app
    networks:
      - shopping_net

networks:
  shopping_net:
    driver: bridge
    ipam:
      driver: default